### ISSUE TITLE
urdf error: chest_link has multiple inertia

### ISSUE THREAD

**Issue by OTL** [ROBOTIS-GIT/ROBOTIS-THORMANG-Common#15]
chest_link of below xacro file has multiple inertia.
It generates illegal format as urdf.

Please comment out it as other links.

https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-Common/blob/master/thormang3_description/urdf/thormang3.xacro

**Comment by s-changhyun** [comment]
We update the urdf file. That was overlap line.

**Comment by OTL** [comment]
It seems to be fixed already! Thanks.
