### ISSUE TITLE
No feet_ft_sensor in gazebo model

### ISSUE THREAD

**Issue by allan2013** [ROBOTIS-GIT/ROBOTIS-THORMANG-Common#18]
In gazebo simulator, there is not any feet_ft_sensor or feet_contact_sensor. Therefore, even balance_control [
"ON" button is pressed on the demo operation panel, Thormang3 cannot walk on balance.  Can you fix it?

**Comment by s-changhyun** [comment]
I have a plan to attach sensors such as 3D Lidar, RGB camera, IMU and FT sensor as soon as possible ! I already tested almost of sensors. Please wait.

**Comment by yilidong** [comment]
I tried to add one gazebo contact sensor plug-in on both of the right and left feet, respectively. However, it seems that the contact sensor can work well individually but fails to work when both are on. Have you met the same trouble?


   <gazebo reference="r_leg_an_r_link">
      <sensor name="r_leg_an_r_link_contact" type="contact">
         <contact>
           	<collision>r_leg_an_r_link_fixed_joint_lump__r_leg_foot_link_collision_1</collision>
         </contact>
         <update_rate> 1000 </update_rate>
         <plugin name="thormang3_contact_r" filename="libthormang3_contact_right.so" />
      </sensor>
    </gazebo>
    
       <gazebo reference="l_leg_an_r_link">
      <sensor name="l_leg_an_r_link_contact" type="contact">
         <contact>
           	<collision>l_leg_an_r_link_fixed_joint_lump__l_leg_foot_link_collision_1</collision>
         </contact>
         <update_rate> 1000 </update_rate>
         <plugin name="thormang3_contact_l" filename="libthormang3_contact_Beft.so" />
      </sensor>
    </gazebo>

**Comment by allan2013** [comment]
There is already a IMU sensor in the model. Do you mean it is not functional?

**Comment by s-changhyun** [comment]
In .gazebo file, I added IMU and camera plugin.
However, I did not set the sensors in .xacro file yet.

**Comment by allan2013** [comment]
I modified your .gazebo file by adding ft_sensor gazebo plugin in an analog way as the following URL.
https://github.com/thor-mang/ROBOTIS-THORMANG-Common
And also I replaced the thormang3_feet_ft_module with the one in the following URL.
https://github.com/thor-mang/ROBOTIS-THORMANG-MPC

But when I pressed the walking_mode button in the demo control panel, the robot vibrated strongly and tumbled eventually. If using the rostopic data from ft_sensor gazebo plugin, should I transform the raw data into some special coordinate fitting well with your balance control and walking module? Does the right and left foot adopt the same coordinate? 

Could you review the URLs above and give me some hints? Thank you.

**Comment by s-changhyun** [comment]
That URL is not our source code and I also cannot review what is changed.

I also do not know what you did because you did not provide anything to us.
Additionally, I want to know how much you understand about the thormang's operation and walking & balance code.

As I told you, I am also trying to update the simulation including sensors.

**Comment by robotpilot** [comment]
Thank you for your consideration and supports. This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
