### ISSUE TITLE
Questions about configurations of Thormang3

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-THORMANG-Common#21]
Hi, I have some questions about configurations of Thormang3

1. Baudrate of Dynamixel Pro used for Thormang3

2. Read cycle of present position

3. How to read information about Dynamixel Pro (including present position) with in 5 ms cycle

4. How fast was the cycle when you participated in DRC?

**Comment by ROBOTIS-zerom** [comment]
Hi, yoshimalucky-san.

1. Default baudrate : 2 Mbps
2. Read cycle : 8 ms
3. How to read : using BulkRead
4. Read cycle in DRC : 8 ms

Check the file below : 
https://github.com/ROBOTIS-GIT/ROBOTIS-Framework/blob/master/robotis_controller/src/robotis_controller/robotis_controller.cpp

about cycle : check void *RobotisController::timerThread(void *param) function.
about bulk read : check void RobotisController::process() function.

bulk read example : http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_bulk_read_write_protocol_2_0/#cpp-bulk-read-write-protocol-20

**Comment by robograffitti** [comment]
Thanks!
